name: Esegui script ogni giorno lavorativo alle 16:15 ora locale 

on:
  schedule:
    - cron: '15 15 * * 1-5'  # Ogni giorno lavorativo alle 15:15 UTC (che è 16:15 CEST)
  workflow_dispatch:  # Permette di eseguire il workflow manualmente tramite l'interfaccia GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v2

      - name: Impostare Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Imposta la versione di Python se necessario

      - name: Installare dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installa le dipendenze dal file requirements.txt

      - name: Esegui script
        run: |
          python3 web_scraping.py  # Sostituisci con il comando per eseguire il tuo script

      - name: Configura l'utente Git
        run: |
          git config --global user.name "apalladi"
          git config --global user.email "andrea.palladino@outlook.it"

      - name: Aggiungi le modifiche al commit
        run: |
          git add results/bond_info_extracted.csv  # Aggiunge tutte le modifiche al commit

      - name: Esegui il commit
        run: |
          git commit -m "Aggiornamento automatico dopo esecuzione script" || echo "Nessuna modifica da commettere"

      - name: Push delle modifiche
        run: |
          git push https://x-access-token:${{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}}@github.com/apalladi/EU_bond_scraping.git

