name: Esegui script ogni giorno lavorativo alle 20:00 ora locale

on:
  schedule:
    - cron: '0 19 * * 1-5'  # Ogni giorno lavorativo alle 19:00 UTC (20:00 ora italiana)
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v2

      - name: Impostare SSH per GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Impostare Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Installare dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Eseguire lo script di web scraping
        run: |
          python3 web_scraping.py  # Esegui il tuo script di scraping

      - name: Configurare Git
        run: |
          git config --global user.name "apalladi"
          git config --global user.email "andrea.palladino@outlook.it"

      - name: Aggiungere e committare modifiche
        run: |
          git add results/bond_info_extracted.csv  # Aggiungi anche i dati estratti dallo scraping
          git commit -m "Aggiornamento automatico dei dati" || echo "Nessuna modifica da commettere"

      - name: Push delle modifiche via SSH
        run: |
          git push git@github.com:apalladi/EU_bond_scraping.git
